name: Generate images
on: [push, workflow_dispatch]

jobs:
  build-image:
    strategy:
      matrix:
        module: ["ip_vs_mh", "ip_vs_nq", "ip_vs_wlc", "ip_vs_ftp", "ip_vs_lblc", "ip_vs_pe_sip", "ip_vs_ovf", "ip_vs_dh", "ip_vs_fo", "ip_vs_wrr", "ip_vs_lblcr", "ip_vs_lc", "ip_vs_sed"]

    name: Build image without Containerfile
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # - name: install deps for multi-arch builds
    #   run: sudo apt-get install -y qemu-user-static
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        base-image: docker.io/alpine:3.17.2
        image: bottlerocket-modprobe
        tags: ${{ matrix.module }}
        entrypoint: chroot /.bottlerocket/rootfs modprobe ${{ matrix.module }}
        # platforms: linux/arm64/v8, linux/amd64, linux/arm/v7, linux/arm/v6
        arch: amd64, arm64, arm

    - name: set lower case owner name
      run: |
        echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
      env:
        OWNER: '${{ github.repository_owner }}'

    - name: Push image to GHCR
      uses: redhat-actions/push-to-registry@v2
      id: push
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
        registry: ghcr.io/${{ env.OWNER_LC }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push.outputs.registry-paths }}"
